#!/usr/bin/env bash
# Rewrite /etc/nginx/snippets/pitsngiggles-wsl2-upstream.conf so Nginx in WSL2
# forwards to the Windows host (Pits n' Giggles on 4768, engineer_voice on 11734).
# On WSL1 or native Linux, the default is 127.0.0.1.
#
# Usage: sudo ./apply-wsl2-nginx-upstreams.sh
#   WSL2_WINDOWS_GW=192.168.1.1  sudo -E ...   # override Windows host IP
set -euo pipefail

OUT="${1:-/etc/nginx/snippets/pitsngiggles-wsl2-upstream.conf}"
WIN="${WSL2_WINDOWS_GW:-}"

if [[ -n "$WIN" ]]; then
  : # use override
elif grep -qi microsoft /proc/version 2>/dev/null; then
  # WSL2: default gateway in the distro is the Windows host
  WIN=$(ip -4 route list default 0.0.0.0/0 2>/dev/null | awk '{print $3; exit}')
  if [[ -z "$WIN" ]]; then
    WIN=$(ip -4 route show default 2>/dev/null | awk '/default/ {print $3; exit}')
  fi
  if [[ -z "$WIN" && -f /etc/resolv.conf ]]; then
    WIN=$(grep -m1 '^nameserver' /etc/resolv.conf 2>/dev/null | awk '{print $2}')
  fi
  if [[ -z "$WIN" ]]; then
    echo "Could not determine Windows host IP; set WSL2_WINDOWS_GW" >&2
    exit 1
  fi
else
  WIN="${PITS_PNG_UPSTREAM:-127.0.0.1}"
fi

mkdir -p "$(dirname "$OUT")"
tmp="$(mktemp)"
{
  echo "# Generated by apply-wsl2-nginx-upstreams.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ) — target_host=${WIN}"
  echo "upstream wsl2_png_4768 {"
  echo "    server ${WIN}:4768;"
  echo "}"
  echo "upstream wsl2_voice_11734 {"
  echo "    server ${WIN}:11734;"
  echo "}"
} > "$tmp"
install -D -m 644 "$tmp" "$OUT"
rm -f "$tmp"
echo "Wrote $OUT (Windows/services host: ${WIN})"
nginx -t
echo "Run: sudo systemctl reload nginx  OR  sudo nginx -s reload"
